### ISSUE TITLE
Numeric only 1,2,3 on Android devices

### ISSUE THREAD

**Issue by pruimmartin** [framework7io/framework7-plugin-keypad#1]
Hi,

I know it is probably not supported, but maybe there's a quick fix for this. On Android devices, only the numbers 1,2,3 are visible when using numeric. They are fully functional, but i miss the other 6 buttons. Tried to change some z-index values in the css file, but none helps. Maybe you know how this could be fixed.

Thanks!

**Comment by mikeymatteo** [comment]
Same problem here on android native browsers.

**Comment by zanurano** [comment]
update 4.2.3

**Comment by zanurano** [comment]
try update android version to 4.2.3 or newer

**Comment by Valkhan** [comment]
Same problem here with Android 4.2.2.

@zanurano Updating Android version for some devices like Galaxy Gran Duos isn't an option as it's not officialy supported.

I'm worried that for more than two years there was no fix for this issue. Sad.
